### ISSUE TITLE
Support for Docking Branch

### ISSUE THREAD

**Issue by KCoen** [aybe/imgui.NET#14]
Hey, thank you very much for making this library.

It would be nice if it could support the docking branch of Imgui, since the project only targets a single Graphics Api and Platform, it would probably be fairly stable and bug free out of the box.

**Comment by aybe** [comment]
You welcome!

As explained in #15, same notes except with probably few notable differences:

One should [ignore some of the types](https://github.com/aybe/DearImGui/blob/develop/DearImGui.Generator/LibraryImGui.cs#L71) and implement them [manually instead](https://github.com/aybe/DearImGui/tree/develop/DearImGui).
That's simply because there are limits as to what CppSharp can do as opposed to writing short classes manually and quickly.

Also, some of the types might need to be mapped, for some of them, I just wrote [T4 templates](https://github.com/aybe/DearImGui/tree/develop/DearGenerator/TypeMaps), i.e. DRY.

Last thing, if you get things right and realize that something isn't visible on the screen, it's probably a marshalling issue, which I resolved [like so](https://github.com/aybe/DearImGui/blob/develop/DearImGui/ImVector.cs#L23). Unfortunately that can't really be generated but the code is very easy to write. In that particular case, native debugging + Memory window in Visual Studio proved to be of great help to understand where the marshalling issue actually was.

**Comment by aybe** [comment]
Forgot to mention, yeah, the docking branch is ahead of +1500 commits or so, it'll probably be a bit more involved. 😅

Basically, you need patience and therefore time, that's pretty much it. Once you get the hang out of the process, it ain't that hard.

**Comment by KCoen** [comment]
Its not at scary as it looks i hope, the Docking branch is quite long running, but merged with every ImGui release, diffing Imgui.h between docking and master on version 1.88, showed 14 removals, and 271 additions.

Most of the changes are multi-window related, which is optional and they automatically detect our back-end doesn't support it, so its not an issue to leave it unimplemented.

I'll investigate how much work that would be at a later time.


Thank you very much for the pointers so far, its been a breeze/blast working on the codebase.

**Comment by aybe** [comment]
I guess we can close this one with your PR 💯!

**Comment by ds5678** [comment]
@aybe can you post a NuGet release with these improvements?

**Comment by aybe** [comment]
Sorry for the late answering, been pretty busy...

Here it is: 

https://www.nuget.org/packages/DearImGui/1.89.3

I've upgraded the code in the mean time, let me know if anything's wrong!

**Comment by ds5678** [comment]
Thank you!
